### ISSUE TITLE
Creating new theme in rooms.yml gives a yellow warning and doesn't use the theme configuration

### ISSUE THREAD

**Issue by mdf25** [JereKuusela/valheim-expand_world#26]
When trying to make a room clone with a new theme, gives yellow warning when you do 2 or more rooms with the new theme

Example: This works:
```yml
- name: forestcrypt_new_Burialchamber04:Darkwoods
  theme: ForestCrypt
  minPlaceOrder: 3
  size: 16,8,6
  connections:
  - position: 4,-4,-1.5,0
- name: forestcrypt_new_Burialchamber05:Darkwoods
  theme: DarkwoodsCrypt
  minPlaceOrder: 3
  size: 16,16,8
  connections:
  - position: -8,0,-1.5,90
  - position: -5,-8,-1.5,0
```
However, if I change the first 'ForestCrypt' theme to 'DarkwoodsCrypt' it gives me the error twice:
```Failed to parse value DarkwoodsCrypt as T.```
If I set the first one to any other theme name aside from ForestCrypt, it also gives me the error, but this time once with 'DarkwoodsCrypt' and once with whatever I called the other theme.
