### ISSUE TITLE
Issue & Suggestion: CampRadial dungeon issues

### ISSUE THREAD

**Issue by mdf25** [JereKuusela/valheim-expand_world#27]
Greetings! I have a couple suggestions for the CampRadial type dungeon for generating villages. I'm trying to make my own using blueprints, but I have run into several problems occurring.

- Using the Terrain markers from PlanBuild's Blueprints doesn't seem to work with Expand World. I tried to export the terrain marker with PlanBuild as part of the prefab and can see it in the .blueprint file, but Expand World says `Cannot find 'circle' prefab` and either completely ignores the terrain marker to adjust height, or spawns the prefab about 4 metres in the air which causes it to just break.

- Using the `levelArea` option to flatten land around a location in `expand_locations` does work for village generation, but I noticed that even though the terrain gets flattened, the prefabs seem to generate first beforehand, resulting in some floating above the land, and others sinking into the ground, making them either destroy themselves or be inaccessible. Happens with both PlanBuild and InfinityHammer specifying a central point of the prefab.

As a suggestion I'd love to see these things implemented to counteract some of the problems:
- In `expand_rooms`, allow us to use a `levelArea` for rooms that use `Camp` or `CampRadial`, with the option for `levelRadius` and `paint`, since the terrain markers from PlanBuild don't seem to preserve that info when read into Expand World.
- In `expand_rooms`, allow us to use `groundOffset` to raise or lower terrain of rooms individually.
- In `expand_locations`, make it so that if `levelArea` is specified for `true`, it will generate blueprints all on the same level after the terrain is flattened (if this is even possible) taking into account the offset and terrain specified in 'expand_rooms'.

My code for the room generation:

```yml
# expand_locations
- prefab: WoodFarm1:GreydwarfVillage
  biome: BlackForest
  quantity: 30
  minAltitude: 3
  dungeon: DG_GreydwarfTown
  group: GreydwarfTown
  minDistanceFromSimilar: 250
  randomRotation: true
  maxTerrainDelta: 10
  exteriorRadius: 32
  clearArea: true
  levelArea: false # I've been altering this from false to true to test some stuff
  levelRadius: 32
  paint: dirt
  biomeArea: median
  randomDamage: true
  groundOffset: 0
  iconPlaced: Hildir_camp

# expand_dungeons
- name: DG_GreydwarfTown
  algorithm: CampRadial
  maxRooms: 30
  minRooms: 20
  minRequiredRooms: 1
  requiredRooms: Greydwarf_Nest_Village
  themes: GreydwarfVillage
  doorTypes: []
  maxTilt: 25
  campRadiusMin: 40
  campRadiusMax: 50
  minAltitude: 1
  perimeterSections: 10
  bounds: 64
  objectSwap:
  - CastleKit_groundtorch_blue, Spawner_Greydwarf_Elite
  - CastleKit_groundtorch, Spawner_Greydwarf_Shaman
  - CastleKit_braided_box01, Spawner_Greydwarf

# expand_rooms
- name: Greydwarf_Nest_Village
  theme: GreydwarfVillage
  weight: 3
  size: 5,5,6
  connections: []
  weight: 0.1
- name: Greydwarf_House_Wood_Large_01
  theme: GreydwarfVillage
  weight: 3
  faceCenter: true
  perimeter: false
  size: 16,16,8
  connections: []
- name: Greydwarf_House_Stone_01
  theme: GreydwarfVillage
  weight: 2
  faceCenter: true
  perimeter: false
  size: 10,10,12
  connections: []
- name: Greydwarf_House_Wood_Small_01
  theme: GreydwarfVillage
  weight: 6
  faceCenter: true
  perimeter: false
  size: 12,12,12
  connections: []
  ```
  
I tried to attach the blueprints, but Github doesn't like it. Happy to send them if needed elsewhere.
